# Generated by Django 4.1.5 on 2023-07-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('imgurl', models.CharField(max_length=300)),
                ('newsurl', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('query', models.CharField(max_length=20)),
                ('date', models.DateField(blank=True)),
            ],
        ),
    ]
